// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/common.dart';
import 'api/engine.dart';
import 'core/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'text_effect/effects.dart';
import 'track/track_manager.dart';
import 'utils/color.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -979739233;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_rs_ffi_barrage',
        ioDirectory: 'native/rs_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiEngineEngineHandleAliveCount({required EngineHandle that});

  void crateApiEngineEngineHandleClear({required EngineHandle that});

  EngineHandle crateApiEngineEngineHandleCreate({
    required int width,
    required int height,
  });

  PlatformInt64 crateApiEngineEngineHandleCurrentTime({
    required EngineHandle that,
  });

  EngineDimensions crateApiEngineEngineHandleDimensions({
    required EngineHandle that,
  });

  void crateApiEngineEngineHandlePause({required EngineHandle that});

  PlayState crateApiEngineEngineHandlePlayState({required EngineHandle that});

  bool crateApiEngineEngineHandlePushBarrage({
    required EngineHandle that,
    required BarrageMsg msg,
  });

  Uint8List crateApiEngineEngineHandleRenderFrame({
    required EngineHandle that,
    required PlatformInt64 timestampMs,
  });

  void crateApiEngineEngineHandleResize({
    required EngineHandle that,
    required int width,
    required int height,
  });

  void crateApiEngineEngineHandleResume({required EngineHandle that});

  void crateApiEngineEngineHandleSeek({
    required EngineHandle that,
    required PlatformInt64 timestampMs,
  });

  void crateApiEngineEngineHandleSetGlobalGradient({
    required EngineHandle that,
    required GradientConfig config,
  });

  void crateApiEngineEngineHandleSetGlobalNeon({
    required EngineHandle that,
    required NeonConfig config,
  });

  void crateApiEngineEngineHandleSetGlobalShadow({
    required EngineHandle that,
    required ShadowConfig config,
  });

  void crateApiEngineEngineHandleSetGlobalStroke({
    required EngineHandle that,
    required StrokeConfig config,
  });

  void crateApiEngineEngineHandleSetSpeed({
    required EngineHandle that,
    required double speed,
  });

  Future<String> crateApiEngineEngineHandleVersion();

  Future<GradientConfig> crateApiCommonGradientConfigDefault();

  Future<NeonConfig> crateApiCommonNeonConfigDefault();

  Future<ShadowConfig> crateApiCommonShadowConfigDefault();

  Future<StrokeConfig> crateApiCommonStrokeConfigDefault();

  Future<TextEffectConfig> crateApiCommonTextEffectConfigDefault();

  Future<TextEffects> crateApiCommonTextEffectConfigToInternal({
    required TextEffectConfig that,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EngineHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EngineHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EngineHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiEngineEngineHandleAliveCount({required EngineHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleAliveCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleAliveCountConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_alive_count",
        argNames: ["that"],
      );

  @override
  void crateApiEngineEngineHandleClear({required EngineHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleClearConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleClearConstMeta =>
      const TaskConstMeta(debugName: "EngineHandle_clear", argNames: ["that"]);

  @override
  EngineHandle crateApiEngineEngineHandleCreate({
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleCreateConstMeta,
        argValues: [width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleCreateConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_create",
        argNames: ["width", "height"],
      );

  @override
  PlatformInt64 crateApiEngineEngineHandleCurrentTime({
    required EngineHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleCurrentTimeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleCurrentTimeConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_current_time",
        argNames: ["that"],
      );

  @override
  EngineDimensions crateApiEngineEngineHandleDimensions({
    required EngineHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_dimensions,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleDimensionsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleDimensionsConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_dimensions",
        argNames: ["that"],
      );

  @override
  void crateApiEngineEngineHandlePause({required EngineHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandlePauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandlePauseConstMeta =>
      const TaskConstMeta(debugName: "EngineHandle_pause", argNames: ["that"]);

  @override
  PlayState crateApiEngineEngineHandlePlayState({required EngineHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_play_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandlePlayStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandlePlayStateConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_play_state",
        argNames: ["that"],
      );

  @override
  bool crateApiEngineEngineHandlePushBarrage({
    required EngineHandle that,
    required BarrageMsg msg,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_barrage_msg(msg, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandlePushBarrageConstMeta,
        argValues: [that, msg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandlePushBarrageConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_push_barrage",
        argNames: ["that", "msg"],
      );

  @override
  Uint8List crateApiEngineEngineHandleRenderFrame({
    required EngineHandle that,
    required PlatformInt64 timestampMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_i_64(timestampMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleRenderFrameConstMeta,
        argValues: [that, timestampMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleRenderFrameConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_render_frame",
        argNames: ["that", "timestampMs"],
      );

  @override
  void crateApiEngineEngineHandleResize({
    required EngineHandle that,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleResizeConstMeta,
        argValues: [that, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleResizeConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_resize",
        argNames: ["that", "width", "height"],
      );

  @override
  void crateApiEngineEngineHandleResume({required EngineHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleResumeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleResumeConstMeta =>
      const TaskConstMeta(debugName: "EngineHandle_resume", argNames: ["that"]);

  @override
  void crateApiEngineEngineHandleSeek({
    required EngineHandle that,
    required PlatformInt64 timestampMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_i_64(timestampMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSeekConstMeta,
        argValues: [that, timestampMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSeekConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_seek",
        argNames: ["that", "timestampMs"],
      );

  @override
  void crateApiEngineEngineHandleSetGlobalGradient({
    required EngineHandle that,
    required GradientConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_gradient_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSetGlobalGradientConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSetGlobalGradientConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_set_global_gradient",
        argNames: ["that", "config"],
      );

  @override
  void crateApiEngineEngineHandleSetGlobalNeon({
    required EngineHandle that,
    required NeonConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_neon_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSetGlobalNeonConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSetGlobalNeonConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_set_global_neon",
        argNames: ["that", "config"],
      );

  @override
  void crateApiEngineEngineHandleSetGlobalShadow({
    required EngineHandle that,
    required ShadowConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_shadow_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSetGlobalShadowConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSetGlobalShadowConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_set_global_shadow",
        argNames: ["that", "config"],
      );

  @override
  void crateApiEngineEngineHandleSetGlobalStroke({
    required EngineHandle that,
    required StrokeConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_stroke_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSetGlobalStrokeConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSetGlobalStrokeConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_set_global_stroke",
        argNames: ["that", "config"],
      );

  @override
  void crateApiEngineEngineHandleSetSpeed({
    required EngineHandle that,
    required double speed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
            that,
            serializer,
          );
          sse_encode_f_64(speed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleSetSpeedConstMeta,
        argValues: [that, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleSetSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "EngineHandle_set_speed",
        argNames: ["that", "speed"],
      );

  @override
  Future<String> crateApiEngineEngineHandleVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineHandleVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineHandleVersionConstMeta =>
      const TaskConstMeta(debugName: "EngineHandle_version", argNames: []);

  @override
  Future<GradientConfig> crateApiCommonGradientConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_gradient_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonGradientConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonGradientConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "gradient_config_default", argNames: []);

  @override
  Future<NeonConfig> crateApiCommonNeonConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_neon_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonNeonConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonNeonConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "neon_config_default", argNames: []);

  @override
  Future<ShadowConfig> crateApiCommonShadowConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shadow_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonShadowConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonShadowConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "shadow_config_default", argNames: []);

  @override
  Future<StrokeConfig> crateApiCommonStrokeConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stroke_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonStrokeConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonStrokeConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "stroke_config_default", argNames: []);

  @override
  Future<TextEffectConfig> crateApiCommonTextEffectConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_effect_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonTextEffectConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonTextEffectConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "text_effect_config_default",
        argNames: [],
      );

  @override
  Future<TextEffects> crateApiCommonTextEffectConfigToInternal({
    required TextEffectConfig that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_text_effect_config(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_effects,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonTextEffectConfigToInternalConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonTextEffectConfigToInternalConstMeta =>
      const TaskConstMeta(
        debugName: "text_effect_config_to_internal",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EngineHandle =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EngineHandle =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle;

  @protected
  EngineHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EngineHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EngineHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BarrageMsg dco_decode_barrage_msg(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BarrageMsg(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      trackType: dco_decode_track_type(arr[2]),
      color: dco_decode_u_32(arr[3]),
      fontSize: dco_decode_f_64(arr[4]),
      timestamp: dco_decode_i_64(arr[5]),
      textEffects: dco_decode_text_effect_config(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BarrageMsg dco_decode_box_autoadd_barrage_msg(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_barrage_msg(raw);
  }

  @protected
  GradientConfig dco_decode_box_autoadd_gradient_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gradient_config(raw);
  }

  @protected
  NeonConfig dco_decode_box_autoadd_neon_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_neon_config(raw);
  }

  @protected
  ShadowConfig dco_decode_box_autoadd_shadow_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shadow_config(raw);
  }

  @protected
  StrokeConfig dco_decode_box_autoadd_stroke_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stroke_config(raw);
  }

  @protected
  TextEffectConfig dco_decode_box_autoadd_text_effect_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_text_effect_config(raw);
  }

  @protected
  Color dco_decode_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Color(
      r: dco_decode_u_8(arr[0]),
      g: dco_decode_u_8(arr[1]),
      b: dco_decode_u_8(arr[2]),
      a: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  EngineDimensions dco_decode_engine_dimensions(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EngineDimensions(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GradientConfig dco_decode_gradient_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GradientConfig(
      enabled: dco_decode_bool(arr[0]),
      gradType: dco_decode_gradient_type(arr[1]),
      colors: dco_decode_list_prim_u_32_strict(arr[2]),
      angle: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  GradientEffect dco_decode_gradient_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GradientEffect(
      enabled: dco_decode_bool(arr[0]),
      gradientType: dco_decode_gradient_type(arr[1]),
      colors: dco_decode_list_color(arr[2]),
      stops: dco_decode_list_prim_f_32_strict(arr[3]),
      angle: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  GradientType dco_decode_gradient_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GradientType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Color> dco_decode_list_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_color).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NeonConfig dco_decode_neon_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NeonConfig(
      enabled: dco_decode_bool(arr[0]),
      radius: dco_decode_f_32(arr[1]),
      color: dco_decode_u_32(arr[2]),
      intensity: dco_decode_f_32(arr[3]),
      layers: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  NeonEffect dco_decode_neon_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NeonEffect(
      enabled: dco_decode_bool(arr[0]),
      radius: dco_decode_f_32(arr[1]),
      color: dco_decode_color(arr[2]),
      intensity: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  PlayState dco_decode_play_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayState.values[raw as int];
  }

  @protected
  ShadowConfig dco_decode_shadow_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ShadowConfig(
      enabled: dco_decode_bool(arr[0]),
      offsetX: dco_decode_f_32(arr[1]),
      offsetY: dco_decode_f_32(arr[2]),
      blur: dco_decode_f_32(arr[3]),
      color: dco_decode_u_32(arr[4]),
      layers: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  ShadowEffect dco_decode_shadow_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ShadowEffect(
      enabled: dco_decode_bool(arr[0]),
      offsetX: dco_decode_f_32(arr[1]),
      offsetY: dco_decode_f_32(arr[2]),
      blur: dco_decode_f_32(arr[3]),
      color: dco_decode_color(arr[4]),
    );
  }

  @protected
  StrokeConfig dco_decode_stroke_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StrokeConfig(
      enabled: dco_decode_bool(arr[0]),
      width: dco_decode_f_32(arr[1]),
      color: dco_decode_u_32(arr[2]),
      isOuter: dco_decode_bool(arr[3]),
    );
  }

  @protected
  StrokeEffect dco_decode_stroke_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StrokeEffect(
      enabled: dco_decode_bool(arr[0]),
      width: dco_decode_f_32(arr[1]),
      color: dco_decode_color(arr[2]),
    );
  }

  @protected
  TextEffectConfig dco_decode_text_effect_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TextEffectConfig(
      stroke: dco_decode_stroke_config(arr[0]),
      shadow: dco_decode_shadow_config(arr[1]),
      neon: dco_decode_neon_config(arr[2]),
      gradient: dco_decode_gradient_config(arr[3]),
    );
  }

  @protected
  TextEffects dco_decode_text_effects(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TextEffects(
      stroke: dco_decode_stroke_effect(arr[0]),
      shadow: dco_decode_shadow_effect(arr[1]),
      neon: dco_decode_neon_effect(arr[2]),
      gradient: dco_decode_gradient_effect(arr[3]),
    );
  }

  @protected
  TrackType dco_decode_track_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrackType.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  EngineHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EngineHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EngineHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BarrageMsg sse_decode_barrage_msg(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_trackType = sse_decode_track_type(deserializer);
    var var_color = sse_decode_u_32(deserializer);
    var var_fontSize = sse_decode_f_64(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_textEffects = sse_decode_text_effect_config(deserializer);
    return BarrageMsg(
      id: var_id,
      text: var_text,
      trackType: var_trackType,
      color: var_color,
      fontSize: var_fontSize,
      timestamp: var_timestamp,
      textEffects: var_textEffects,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BarrageMsg sse_decode_box_autoadd_barrage_msg(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_barrage_msg(deserializer));
  }

  @protected
  GradientConfig sse_decode_box_autoadd_gradient_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gradient_config(deserializer));
  }

  @protected
  NeonConfig sse_decode_box_autoadd_neon_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_neon_config(deserializer));
  }

  @protected
  ShadowConfig sse_decode_box_autoadd_shadow_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_shadow_config(deserializer));
  }

  @protected
  StrokeConfig sse_decode_box_autoadd_stroke_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stroke_config(deserializer));
  }

  @protected
  TextEffectConfig sse_decode_box_autoadd_text_effect_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_text_effect_config(deserializer));
  }

  @protected
  Color sse_decode_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_r = sse_decode_u_8(deserializer);
    var var_g = sse_decode_u_8(deserializer);
    var var_b = sse_decode_u_8(deserializer);
    var var_a = sse_decode_u_8(deserializer);
    return Color(r: var_r, g: var_g, b: var_b, a: var_a);
  }

  @protected
  EngineDimensions sse_decode_engine_dimensions(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return EngineDimensions(width: var_width, height: var_height);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GradientConfig sse_decode_gradient_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_gradType = sse_decode_gradient_type(deserializer);
    var var_colors = sse_decode_list_prim_u_32_strict(deserializer);
    var var_angle = sse_decode_f_32(deserializer);
    return GradientConfig(
      enabled: var_enabled,
      gradType: var_gradType,
      colors: var_colors,
      angle: var_angle,
    );
  }

  @protected
  GradientEffect sse_decode_gradient_effect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_gradientType = sse_decode_gradient_type(deserializer);
    var var_colors = sse_decode_list_color(deserializer);
    var var_stops = sse_decode_list_prim_f_32_strict(deserializer);
    var var_angle = sse_decode_f_32(deserializer);
    return GradientEffect(
      enabled: var_enabled,
      gradientType: var_gradientType,
      colors: var_colors,
      stops: var_stops,
      angle: var_angle,
    );
  }

  @protected
  GradientType sse_decode_gradient_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GradientType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Color> sse_decode_list_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Color>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_color(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NeonConfig sse_decode_neon_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_radius = sse_decode_f_32(deserializer);
    var var_color = sse_decode_u_32(deserializer);
    var var_intensity = sse_decode_f_32(deserializer);
    var var_layers = sse_decode_u_32(deserializer);
    return NeonConfig(
      enabled: var_enabled,
      radius: var_radius,
      color: var_color,
      intensity: var_intensity,
      layers: var_layers,
    );
  }

  @protected
  NeonEffect sse_decode_neon_effect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_radius = sse_decode_f_32(deserializer);
    var var_color = sse_decode_color(deserializer);
    var var_intensity = sse_decode_f_32(deserializer);
    return NeonEffect(
      enabled: var_enabled,
      radius: var_radius,
      color: var_color,
      intensity: var_intensity,
    );
  }

  @protected
  PlayState sse_decode_play_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayState.values[inner];
  }

  @protected
  ShadowConfig sse_decode_shadow_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_offsetX = sse_decode_f_32(deserializer);
    var var_offsetY = sse_decode_f_32(deserializer);
    var var_blur = sse_decode_f_32(deserializer);
    var var_color = sse_decode_u_32(deserializer);
    var var_layers = sse_decode_u_32(deserializer);
    return ShadowConfig(
      enabled: var_enabled,
      offsetX: var_offsetX,
      offsetY: var_offsetY,
      blur: var_blur,
      color: var_color,
      layers: var_layers,
    );
  }

  @protected
  ShadowEffect sse_decode_shadow_effect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_offsetX = sse_decode_f_32(deserializer);
    var var_offsetY = sse_decode_f_32(deserializer);
    var var_blur = sse_decode_f_32(deserializer);
    var var_color = sse_decode_color(deserializer);
    return ShadowEffect(
      enabled: var_enabled,
      offsetX: var_offsetX,
      offsetY: var_offsetY,
      blur: var_blur,
      color: var_color,
    );
  }

  @protected
  StrokeConfig sse_decode_stroke_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_color = sse_decode_u_32(deserializer);
    var var_isOuter = sse_decode_bool(deserializer);
    return StrokeConfig(
      enabled: var_enabled,
      width: var_width,
      color: var_color,
      isOuter: var_isOuter,
    );
  }

  @protected
  StrokeEffect sse_decode_stroke_effect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_color = sse_decode_color(deserializer);
    return StrokeEffect(
      enabled: var_enabled,
      width: var_width,
      color: var_color,
    );
  }

  @protected
  TextEffectConfig sse_decode_text_effect_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stroke = sse_decode_stroke_config(deserializer);
    var var_shadow = sse_decode_shadow_config(deserializer);
    var var_neon = sse_decode_neon_config(deserializer);
    var var_gradient = sse_decode_gradient_config(deserializer);
    return TextEffectConfig(
      stroke: var_stroke,
      shadow: var_shadow,
      neon: var_neon,
      gradient: var_gradient,
    );
  }

  @protected
  TextEffects sse_decode_text_effects(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stroke = sse_decode_stroke_effect(deserializer);
    var var_shadow = sse_decode_shadow_effect(deserializer);
    var var_neon = sse_decode_neon_effect(deserializer);
    var var_gradient = sse_decode_gradient_effect(deserializer);
    return TextEffects(
      stroke: var_stroke,
      shadow: var_shadow,
      neon: var_neon,
      gradient: var_gradient,
    );
  }

  @protected
  TrackType sse_decode_track_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrackType.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EngineHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_barrage_msg(BarrageMsg self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_track_type(self.trackType, serializer);
    sse_encode_u_32(self.color, serializer);
    sse_encode_f_64(self.fontSize, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_text_effect_config(self.textEffects, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_barrage_msg(
    BarrageMsg self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_barrage_msg(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gradient_config(
    GradientConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gradient_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_neon_config(
    NeonConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_neon_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shadow_config(
    ShadowConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shadow_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_stroke_config(
    StrokeConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stroke_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_text_effect_config(
    TextEffectConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_text_effect_config(self, serializer);
  }

  @protected
  void sse_encode_color(Color self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.r, serializer);
    sse_encode_u_8(self.g, serializer);
    sse_encode_u_8(self.b, serializer);
    sse_encode_u_8(self.a, serializer);
  }

  @protected
  void sse_encode_engine_dimensions(
    EngineDimensions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_gradient_config(
    GradientConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_gradient_type(self.gradType, serializer);
    sse_encode_list_prim_u_32_strict(self.colors, serializer);
    sse_encode_f_32(self.angle, serializer);
  }

  @protected
  void sse_encode_gradient_effect(
    GradientEffect self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_gradient_type(self.gradientType, serializer);
    sse_encode_list_color(self.colors, serializer);
    sse_encode_list_prim_f_32_strict(self.stops, serializer);
    sse_encode_f_32(self.angle, serializer);
  }

  @protected
  void sse_encode_gradient_type(GradientType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_color(List<Color> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_color(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_neon_config(NeonConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.radius, serializer);
    sse_encode_u_32(self.color, serializer);
    sse_encode_f_32(self.intensity, serializer);
    sse_encode_u_32(self.layers, serializer);
  }

  @protected
  void sse_encode_neon_effect(NeonEffect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.radius, serializer);
    sse_encode_color(self.color, serializer);
    sse_encode_f_32(self.intensity, serializer);
  }

  @protected
  void sse_encode_play_state(PlayState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_shadow_config(ShadowConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.offsetX, serializer);
    sse_encode_f_32(self.offsetY, serializer);
    sse_encode_f_32(self.blur, serializer);
    sse_encode_u_32(self.color, serializer);
    sse_encode_u_32(self.layers, serializer);
  }

  @protected
  void sse_encode_shadow_effect(ShadowEffect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.offsetX, serializer);
    sse_encode_f_32(self.offsetY, serializer);
    sse_encode_f_32(self.blur, serializer);
    sse_encode_color(self.color, serializer);
  }

  @protected
  void sse_encode_stroke_config(StrokeConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_u_32(self.color, serializer);
    sse_encode_bool(self.isOuter, serializer);
  }

  @protected
  void sse_encode_stroke_effect(StrokeEffect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_color(self.color, serializer);
  }

  @protected
  void sse_encode_text_effect_config(
    TextEffectConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stroke_config(self.stroke, serializer);
    sse_encode_shadow_config(self.shadow, serializer);
    sse_encode_neon_config(self.neon, serializer);
    sse_encode_gradient_config(self.gradient, serializer);
  }

  @protected
  void sse_encode_text_effects(TextEffects self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stroke_effect(self.stroke, serializer);
    sse_encode_shadow_effect(self.shadow, serializer);
    sse_encode_neon_effect(self.neon, serializer);
    sse_encode_gradient_effect(self.gradient, serializer);
  }

  @protected
  void sse_encode_track_type(TrackType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class EngineHandleImpl extends RustOpaque implements EngineHandle {
  // Not to be used by end users
  EngineHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EngineHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_EngineHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_EngineHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_EngineHandlePtr,
  );

  int aliveCount() =>
      RustLib.instance.api.crateApiEngineEngineHandleAliveCount(that: this);

  void clear() =>
      RustLib.instance.api.crateApiEngineEngineHandleClear(that: this);

  PlatformInt64 currentTime() =>
      RustLib.instance.api.crateApiEngineEngineHandleCurrentTime(that: this);

  EngineDimensions dimensions() =>
      RustLib.instance.api.crateApiEngineEngineHandleDimensions(that: this);

  void pause() =>
      RustLib.instance.api.crateApiEngineEngineHandlePause(that: this);

  PlayState playState() =>
      RustLib.instance.api.crateApiEngineEngineHandlePlayState(that: this);

  bool pushBarrage({required BarrageMsg msg}) => RustLib.instance.api
      .crateApiEngineEngineHandlePushBarrage(that: this, msg: msg);

  Uint8List renderFrame({required PlatformInt64 timestampMs}) =>
      RustLib.instance.api.crateApiEngineEngineHandleRenderFrame(
        that: this,
        timestampMs: timestampMs,
      );

  void resize({required int width, required int height}) =>
      RustLib.instance.api.crateApiEngineEngineHandleResize(
        that: this,
        width: width,
        height: height,
      );

  void resume() =>
      RustLib.instance.api.crateApiEngineEngineHandleResume(that: this);

  void seek({required PlatformInt64 timestampMs}) => RustLib.instance.api
      .crateApiEngineEngineHandleSeek(that: this, timestampMs: timestampMs);

  void setGlobalGradient({required GradientConfig config}) => RustLib
      .instance
      .api
      .crateApiEngineEngineHandleSetGlobalGradient(that: this, config: config);

  void setGlobalNeon({required NeonConfig config}) => RustLib.instance.api
      .crateApiEngineEngineHandleSetGlobalNeon(that: this, config: config);

  void setGlobalShadow({required ShadowConfig config}) => RustLib.instance.api
      .crateApiEngineEngineHandleSetGlobalShadow(that: this, config: config);

  void setGlobalStroke({required StrokeConfig config}) => RustLib.instance.api
      .crateApiEngineEngineHandleSetGlobalStroke(that: this, config: config);

  void setSpeed({required double speed}) => RustLib.instance.api
      .crateApiEngineEngineHandleSetSpeed(that: this, speed: speed);
}
