// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/common.dart';
import 'api/engine.dart';
import 'core/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'text_effect/effects.dart';
import 'track/track_manager.dart';
import 'utils/color.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EngineHandlePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle;

  @protected
  EngineHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  );

  @protected
  EngineHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  );

  @protected
  EngineHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BarrageMsg dco_decode_barrage_msg(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BarrageMsg dco_decode_box_autoadd_barrage_msg(dynamic raw);

  @protected
  GradientConfig dco_decode_box_autoadd_gradient_config(dynamic raw);

  @protected
  NeonConfig dco_decode_box_autoadd_neon_config(dynamic raw);

  @protected
  ShadowConfig dco_decode_box_autoadd_shadow_config(dynamic raw);

  @protected
  StrokeConfig dco_decode_box_autoadd_stroke_config(dynamic raw);

  @protected
  TextEffectConfig dco_decode_box_autoadd_text_effect_config(dynamic raw);

  @protected
  Color dco_decode_color(dynamic raw);

  @protected
  EngineDimensions dco_decode_engine_dimensions(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GradientConfig dco_decode_gradient_config(dynamic raw);

  @protected
  GradientEffect dco_decode_gradient_effect(dynamic raw);

  @protected
  GradientType dco_decode_gradient_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Color> dco_decode_list_color(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NeonConfig dco_decode_neon_config(dynamic raw);

  @protected
  NeonEffect dco_decode_neon_effect(dynamic raw);

  @protected
  PlayState dco_decode_play_state(dynamic raw);

  @protected
  ShadowConfig dco_decode_shadow_config(dynamic raw);

  @protected
  ShadowEffect dco_decode_shadow_effect(dynamic raw);

  @protected
  StrokeConfig dco_decode_stroke_config(dynamic raw);

  @protected
  StrokeEffect dco_decode_stroke_effect(dynamic raw);

  @protected
  TextEffectConfig dco_decode_text_effect_config(dynamic raw);

  @protected
  TextEffects dco_decode_text_effects(dynamic raw);

  @protected
  TrackType dco_decode_track_type(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  EngineHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  );

  @protected
  EngineHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  );

  @protected
  EngineHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BarrageMsg sse_decode_barrage_msg(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BarrageMsg sse_decode_box_autoadd_barrage_msg(SseDeserializer deserializer);

  @protected
  GradientConfig sse_decode_box_autoadd_gradient_config(
    SseDeserializer deserializer,
  );

  @protected
  NeonConfig sse_decode_box_autoadd_neon_config(SseDeserializer deserializer);

  @protected
  ShadowConfig sse_decode_box_autoadd_shadow_config(
    SseDeserializer deserializer,
  );

  @protected
  StrokeConfig sse_decode_box_autoadd_stroke_config(
    SseDeserializer deserializer,
  );

  @protected
  TextEffectConfig sse_decode_box_autoadd_text_effect_config(
    SseDeserializer deserializer,
  );

  @protected
  Color sse_decode_color(SseDeserializer deserializer);

  @protected
  EngineDimensions sse_decode_engine_dimensions(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GradientConfig sse_decode_gradient_config(SseDeserializer deserializer);

  @protected
  GradientEffect sse_decode_gradient_effect(SseDeserializer deserializer);

  @protected
  GradientType sse_decode_gradient_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Color> sse_decode_list_color(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NeonConfig sse_decode_neon_config(SseDeserializer deserializer);

  @protected
  NeonEffect sse_decode_neon_effect(SseDeserializer deserializer);

  @protected
  PlayState sse_decode_play_state(SseDeserializer deserializer);

  @protected
  ShadowConfig sse_decode_shadow_config(SseDeserializer deserializer);

  @protected
  ShadowEffect sse_decode_shadow_effect(SseDeserializer deserializer);

  @protected
  StrokeConfig sse_decode_stroke_config(SseDeserializer deserializer);

  @protected
  StrokeEffect sse_decode_stroke_effect(SseDeserializer deserializer);

  @protected
  TextEffectConfig sse_decode_text_effect_config(SseDeserializer deserializer);

  @protected
  TextEffects sse_decode_text_effects(SseDeserializer deserializer);

  @protected
  TrackType sse_decode_track_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    EngineHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_barrage_msg(BarrageMsg self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_barrage_msg(
    BarrageMsg self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gradient_config(
    GradientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_neon_config(
    NeonConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_shadow_config(
    ShadowConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stroke_config(
    StrokeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_text_effect_config(
    TextEffectConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_color(Color self, SseSerializer serializer);

  @protected
  void sse_encode_engine_dimensions(
    EngineDimensions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gradient_config(
    GradientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gradient_effect(
    GradientEffect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gradient_type(GradientType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_color(List<Color> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_neon_config(NeonConfig self, SseSerializer serializer);

  @protected
  void sse_encode_neon_effect(NeonEffect self, SseSerializer serializer);

  @protected
  void sse_encode_play_state(PlayState self, SseSerializer serializer);

  @protected
  void sse_encode_shadow_config(ShadowConfig self, SseSerializer serializer);

  @protected
  void sse_encode_shadow_effect(ShadowEffect self, SseSerializer serializer);

  @protected
  void sse_encode_stroke_config(StrokeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_stroke_effect(StrokeEffect self, SseSerializer serializer);

  @protected
  void sse_encode_text_effect_config(
    TextEffectConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_text_effects(TextEffects self, SseSerializer serializer);

  @protected
  void sse_encode_track_type(TrackType self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineHandle(
    int ptr,
  );
}
