// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../text_effect/effects.dart';
import '../track/track_manager.dart';
import '../utils/color.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BarrageMsg {
  final String id;
  final String text;
  final TrackType trackType;
  final int color;
  final double fontSize;
  final PlatformInt64 timestamp;
  final TextEffectConfig textEffects;

  const BarrageMsg({
    required this.id,
    required this.text,
    required this.trackType,
    required this.color,
    required this.fontSize,
    required this.timestamp,
    required this.textEffects,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      trackType.hashCode ^
      color.hashCode ^
      fontSize.hashCode ^
      timestamp.hashCode ^
      textEffects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarrageMsg &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          trackType == other.trackType &&
          color == other.color &&
          fontSize == other.fontSize &&
          timestamp == other.timestamp &&
          textEffects == other.textEffects;
}

class GradientConfig {
  final bool enabled;
  final GradientType gradType;
  final Uint32List colors;
  final double angle;

  const GradientConfig({
    required this.enabled,
    required this.gradType,
    required this.colors,
    required this.angle,
  });

  static Future<GradientConfig> default_() =>
      RustLib.instance.api.crateApiCommonGradientConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^ gradType.hashCode ^ colors.hashCode ^ angle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GradientConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          gradType == other.gradType &&
          colors == other.colors &&
          angle == other.angle;
}

class NeonConfig {
  final bool enabled;
  final double radius;
  final int color;
  final double intensity;
  final int layers;

  const NeonConfig({
    required this.enabled,
    required this.radius,
    required this.color,
    required this.intensity,
    required this.layers,
  });

  static Future<NeonConfig> default_() =>
      RustLib.instance.api.crateApiCommonNeonConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      radius.hashCode ^
      color.hashCode ^
      intensity.hashCode ^
      layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeonConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          radius == other.radius &&
          color == other.color &&
          intensity == other.intensity &&
          layers == other.layers;
}

class ShadowConfig {
  final bool enabled;
  final double offsetX;
  final double offsetY;
  final double blur;
  final int color;
  final int layers;

  const ShadowConfig({
    required this.enabled,
    required this.offsetX,
    required this.offsetY,
    required this.blur,
    required this.color,
    required this.layers,
  });

  static Future<ShadowConfig> default_() =>
      RustLib.instance.api.crateApiCommonShadowConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      offsetX.hashCode ^
      offsetY.hashCode ^
      blur.hashCode ^
      color.hashCode ^
      layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShadowConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          offsetX == other.offsetX &&
          offsetY == other.offsetY &&
          blur == other.blur &&
          color == other.color &&
          layers == other.layers;
}

class StrokeConfig {
  final bool enabled;
  final double width;
  final int color;
  final bool isOuter;

  const StrokeConfig({
    required this.enabled,
    required this.width,
    required this.color,
    required this.isOuter,
  });

  static Future<StrokeConfig> default_() =>
      RustLib.instance.api.crateApiCommonStrokeConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^ width.hashCode ^ color.hashCode ^ isOuter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrokeConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          width == other.width &&
          color == other.color &&
          isOuter == other.isOuter;
}

class TextEffectConfig {
  final StrokeConfig stroke;
  final ShadowConfig shadow;
  final NeonConfig neon;
  final GradientConfig gradient;

  const TextEffectConfig({
    required this.stroke,
    required this.shadow,
    required this.neon,
    required this.gradient,
  });

  static Future<TextEffectConfig> default_() =>
      RustLib.instance.api.crateApiCommonTextEffectConfigDefault();

  Future<TextEffects> toInternal() =>
      RustLib.instance.api.crateApiCommonTextEffectConfigToInternal(that: this);

  @override
  int get hashCode =>
      stroke.hashCode ^ shadow.hashCode ^ neon.hashCode ^ gradient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextEffectConfig &&
          runtimeType == other.runtimeType &&
          stroke == other.stroke &&
          shadow == other.shadow &&
          neon == other.neon &&
          gradient == other.gradient;
}
