// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/engine.dart';
import '../frb_generated.dart';
import '../text_effect/effects.dart';
import '../track/track_manager.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EngineHandle>>
abstract class EngineHandle implements RustOpaqueInterface {
  int aliveCount();

  void clear();

  static EngineHandle create({required int width, required int height}) =>
      RustLib.instance.api.crateApiEngineEngineHandleCreate(
        width: width,
        height: height,
      );

  PlatformInt64 currentTime();

  EngineDimensions dimensions();

  void pause();

  PlayState playState();

  bool pushBarrage({required BarrageMsg msg});

  Uint8List renderFrame({required PlatformInt64 timestampMs});

  void resize({required int width, required int height});

  void resume();

  void seek({required PlatformInt64 timestampMs});

  void setGlobalGradient({required GradientConfig config});

  void setGlobalNeon({required NeonConfig config});

  void setGlobalShadow({required ShadowConfig config});

  void setGlobalStroke({required StrokeConfig config});

  void setSpeed({required double speed});

  static Future<String> version() =>
      RustLib.instance.api.crateApiEngineEngineHandleVersion();
}

class EngineDimensions {
  final int width;
  final int height;

  const EngineDimensions({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineDimensions &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
