// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/color.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 渐变特效
class GradientEffect {
  final bool enabled;

  /// 渐变类型
  final GradientType gradientType;

  /// 渐变颜色数组
  final List<Color> colors;

  /// 渐变停止位置（0.0 ~ 1.0）
  final Float32List stops;

  /// 渐变角度（度，仅线性渐变有效）
  final double angle;

  const GradientEffect({
    required this.enabled,
    required this.gradientType,
    required this.colors,
    required this.stops,
    required this.angle,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      gradientType.hashCode ^
      colors.hashCode ^
      stops.hashCode ^
      angle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GradientEffect &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          gradientType == other.gradientType &&
          colors == other.colors &&
          stops == other.stops &&
          angle == other.angle;
}

enum GradientType {
  /// 线性渐变
  linear,

  /// 径向渐变
  radial,

  /// 彩虹渐变
  rainbow,
}

/// 霓虹发光特效
class NeonEffect {
  final bool enabled;

  /// 发光半径
  final double radius;

  /// 发光颜色
  final Color color;

  /// 发光强度（0.0 ~ 3.0）
  final double intensity;

  const NeonEffect({
    required this.enabled,
    required this.radius,
    required this.color,
    required this.intensity,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ radius.hashCode ^ color.hashCode ^ intensity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeonEffect &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          radius == other.radius &&
          color == other.color &&
          intensity == other.intensity;
}

/// 阴影特效
class ShadowEffect {
  final bool enabled;

  /// X 轴偏移
  final double offsetX;

  /// Y 轴偏移
  final double offsetY;

  /// 模糊半径
  final double blur;

  /// 阴影颜色
  final Color color;

  const ShadowEffect({
    required this.enabled,
    required this.offsetX,
    required this.offsetY,
    required this.blur,
    required this.color,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      offsetX.hashCode ^
      offsetY.hashCode ^
      blur.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShadowEffect &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          offsetX == other.offsetX &&
          offsetY == other.offsetY &&
          blur == other.blur &&
          color == other.color;
}

/// 描边特效
class StrokeEffect {
  final bool enabled;

  /// 描边宽度（像素）
  final double width;

  /// 描边颜色
  final Color color;

  const StrokeEffect({
    required this.enabled,
    required this.width,
    required this.color,
  });

  @override
  int get hashCode => enabled.hashCode ^ width.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrokeEffect &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          width == other.width &&
          color == other.color;
}

/// 全局文字特效配置集合
class TextEffects {
  final StrokeEffect stroke;
  final ShadowEffect shadow;
  final NeonEffect neon;
  final GradientEffect gradient;

  const TextEffects({
    required this.stroke,
    required this.shadow,
    required this.neon,
    required this.gradient,
  });

  @override
  int get hashCode =>
      stroke.hashCode ^ shadow.hashCode ^ neon.hashCode ^ gradient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextEffects &&
          runtimeType == other.runtimeType &&
          stroke == other.stroke &&
          shadow == other.shadow &&
          neon == other.neon &&
          gradient == other.gradient;
}
