// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 弹幕轨道类型
enum TrackType {
  /// 滚动轨道（从右到左）
  scroll,

  /// 顶部固定轨道
  top,

  /// 底部固定轨道
  bottom,

  /// 逆向滚动轨道（从左到右）
  reverse,
}
